### PR TITLE
Talk proposal from Jarod Reyes. How we threw out the book and put code first with Twilio documentation.

### PR DESCRIPTION
**Pull request by jarodreyes**

### CODE REVIEW

**Comment by thoward** [comment]
Thanks for the proposal! 

(as an aside, maybe I'll make stickers this year that say "Fuck yeah, Jarod Reyes!")

**Comment by jarodreyes** [comment]
@thoward Hahaha, make a few extra for my mom, she would love that ;)

**Comment by adron-orange** [comment]
All these ideas I love, inclusive of the "Fuck yeah, Jarod Reyes!" stickers.

:+1:

**Comment by Adron** [comment]
Hey @jarodreyes what's a good email we can ping you at?

**Comment by jarodreyes** [comment]
jarodreyes@gmail.com my brother.

**Pull request merged**
