### PR TITLE
adding surviving web security by gergely nemeth

### PR DESCRIPTION
**Pull request by gergelyke**

### CODE REVIEW

**Comment by thoward** [comment]
Thanks! Please note that conference dates are June 19-21 (was moved from April).

**Comment by gergelyke** [comment]
Oh yeah, forgot to update that part :)

**Comment by gergelyke** [comment]
How will the selection process go? Didn't find it on the website

**Comment by thoward** [comment]
After we close the CFP (May 1st), our organizing team will review the proposals. Each person on the team can vote for the talks they prefer (they are given a certain amount of points to allocate as they see fit). That will create a basic sort. From there, our CFP Track Czars (software/hardware respectively) will make the hard decisions on exactly which talks are accepted. At that time, we will notify the folks whose talks were accepted (this should be roughly May 10th).

**Comment by gergelyke** [comment]
Got it, thanks!

**Pull request merged**
